Updated git submodules
Project: cef dev-3112 48f0926c60c854604d1d5a92ac46d6307514ae37

Remove unused gn argument


Merge branch 'dev-3112' of github.com:LiuLang/cef into dev-3112


Support atomic operation on mips64el


Add more gn arguments


Support overriding paths

Merge patch from https://github.com/chromiumembedded/cef/pull/4
Issue link is https://github.com/cztomczak/cefpython/issues/231


Disable kerberos


Add more gn options


Support IME on linux


Added default gn args for linux platform


Windows: Fix crash during window creation (see https://crbug.com/761389)


Windows: Wait for WM_NCDESTROY before calling OnBeforeClose (issue #2248)


Update to Chromium version 60.0.3112.113


Windows: Fix crash during window creation (see https://crbug.com/761389)


Windows: Wait for WM_NCDESTROY before calling OnBeforeClose (issue #2248)


Support atomic operation on mips64el


Add more gn arguments


Update to Chromium version 60.0.3112.113


Support overriding paths

Merge patch from https://github.com/chromiumembedded/cef/pull/4
Issue link is https://github.com/cztomczak/cefpython/issues/231


Disable kerberos


Add more gn options


Support IME on linux


Added default gn args for linux platform


Fix Widevine DRM loading


Update to Chromium version 60.0.3112.90


views: Fix LabelButton size calculation


Linux: Work around gold linker bug for 32-bit code.


Fix encoding of linux_build.patch


Fix encoding of linux_build.patch


Linux: Fix build error related to GTK dependency version.


Update to Chromium version 60.0.3112.78


Linux/Mac: Fix handling of command-line arguments (issue #2208)


Windows: Build cef_sandbox.lib with different GN args for official binary distributions (issue #2220)


Add support for loading certificate revocation lists (issue #2213)


Fix incorrect OSR browser display during navigation (issue #2209)


Fix OSR PDF mouse events after keyboard input (issue #2078)


Update to Chromium version 60.0.3112.40


Fix OSR PDF mouse wheel scrolling (issue #2078)


Windows: cefclient: Fix ATL-related build errors (issue #2200)


Linux: Don't pass NULL CefBrowser to PrintHandler::GetPdfPaperSize (issue #2199)


Linux: Pass CefBrowser to CefPrintHandler callbacks (issue #2196)


Fix gtest path (issue #2188)


macOS: Fix error: unknown type name 'size_t'


Linux: Update to debian jessie sysroots


Linux: Fix error: use of undeclared identifier 'GetPreferredSize'


Update to Chromium version 60.0.3112.10